// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_HardwareInterface.cpp"
#include "EWIEGA46WW/moc_gamepage.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_playpage.cpp"
#include "EWIEGA46WW/moc_scorespage.cpp"
